<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="8.10.0" />
        <PackageReference Include="coverlet.collector" Version="10.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="ModelContextProtocol.Core" Version="2.2.0" />
        <PackageReference Include="XTerm.NET" Version="1.0.15" />
        <PackageReference Include="ZmqSharp" Version="0.5.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Maieutics.Agent\Maieutics.Agent.csproj" />
        <ProjectReference Include="..\Maieutics.Jupyter.Client\Maieutics.Jupyter.Client.csproj" />
        <ProjectReference Include="..\Maieutics.Jupyter.Kernel\Maieutics.Jupyter.Kernel.csproj" />
        <ProjectReference Include="..\Maieutics.Jupyter.Shared\Maieutics.Jupyter.Shared.csproj" />
        <ProjectReference Include="..\Maieutics\Maieutics.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <None Include="TestData\kernels\deno\kernel.json" CopyToOutputDirectory="PreserveNewest" />
        <None Include="..\Maieutics\kernelspec\kernel.json" Link="TestData\kernels\maieutics\kernel.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
